### ISSUE TITLE
Error in wordle??

### ISSUE THREAD

**Issue by iweinstein** [im6/wordle#25]
I'm playing the NYtimes version of wordle and entered this guess "elegy", the response colors are 'yybbg'.

I interpret this to mean : 
e is in the solution but not in first position
l is in the solution but not in second position
e is  NOT in the solution ???
g is not in the solution
y is in the solution in fifth position

Is my thinking wrong?

**Comment by im6** [comment]
@iweinstein thanks for the feedback
Do you mind providing the answer word?
I've looked into the code and could not replicate the issue you mentioned.

**Comment by iweinstein** [comment]
Sorry to take so long. I couldn;t reproduce this situation on wordle. But
here's the same situation on wordle archive. The answer word for this one
is HOARD.

What do you think?



[image: wordle261.png]
